2024-08-13 10:37:45,573 Getting artifact
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m artifacts must be specified as 'collection:alias' (Error 400: Bad Request)
Traceback (most recent call last):
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\apis\public\api.py", line 1034, in artifact
    artifact = wandb.Artifact._from_name(
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\artifacts\artifact.py", line 258, in _from_name
    response = client.execute(
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\lib\retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\apis\public\api.py", line 70, in execute
    return self._client.execute(*args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jahaz\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\jahaz\OneDrive\Escritorio\Test\Machine-Learning-DevOps-Engineer\03_Building_reproducible_model_workflow\02_machine_learning_pipelines\01_versioning_data_and_artifacts\solution\use_artifact.py", line 41, in <module>
    go(args)
  File "C:\Users\jahaz\OneDrive\Escritorio\Test\Machine-Learning-DevOps-Engineer\03_Building_reproducible_model_workflow\02_machine_learning_pipelines\01_versioning_data_and_artifacts\solution\use_artifact.py", line 19, in go
    artifact = run.use_artifact(args.artifact_name)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\sdk\wandb_run.py", line 2983, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "C:\Users\jahaz\.conda\envs\udacity_mlops\lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: artifacts must be specified as 'collection:alias' (Error 400: Bad Request)